###EschatologicalUnit.Reward配置文件###
#该插件为OurWorld服务器EschatologicalUnit小游戏项目的一个原创插件
#奖励插件

config:
  prefix: "[EschatologicalUnit]"   #插件提示消息的前缀
  URL: http://127.0.0.1/   #战绩API地址
  
  #发放奖励所需的指令
  #%PlayerID%将会被玩家ID替换
  #%Wave%将会被该战局所坚持的波数替换
  #%Point%将会被对应玩家的分数替换
  Reward_cmd:   
  - say 奖励已发放
  - give %PlayerID% apple %Wave%